In [1]:
import  numpy as np
import pandas as pd

In [5]:
# Read with latin-1 encoding (handles the problematic characters)
df = pd.read_csv('superstore.csv', encoding='latin-1')

# Save back as proper UTF-8
df.to_csv('superstore_utf8.csv', index=False, encoding='utf-8')

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
print(df.shape)

(9994, 21)

In [8]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [9]:
print(df.dtypes)

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [10]:
print(df.isnull().sum())

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [11]:
print("duplicated_rows:",df.duplicated().sum())

duplicated_rows: 0

In [12]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [13]:
# Remove spaces and make all column names lowercase
df.columns = df.columns.str.strip()           
df.columns = df.columns.str.lower()           
df.columns = df.columns.str.replace(' ', '_')

In [14]:
print(df.columns)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub-category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

In [15]:
# Convert Order Date and Ship Date to datetime
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [16]:
df.head(2)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [17]:
# Make sure Sales, Profit, Discount are numeric
df['sales'] = pd.to_numeric(df['sales'], errors='coerce')
df['profit'] = pd.to_numeric(df['profit'], errors='coerce')
df['discount'] = pd.to_numeric(df['discount'], errors='coerce')
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
print(df.dtypes)

row_id                    int64
order_id                 object
order_date       datetime64[ns]
ship_date        datetime64[ns]
ship_mode                object
customer_id              object
customer_name            object
segment                  object
country                  object
city                     object
state                    object
postal_code               int64
region                   object
product_id               object
category                 object
sub-category             object
product_name             object
sales                   float64
quantity                  int64
discount                float64
profit                  float64
dtype: object

In [18]:
#handling missing values 
# Check missing values again after type conversion
print(df.isnull().sum())

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub-category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [19]:
# Verify no missing values remain
print(df.isnull().sum())

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub-category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [20]:
# For numeric columns — fill missing with 0 or median
df['sales'].fillna(df['sales'].median(), inplace=True)
df['profit'].fillna(0, inplace=True)
df['discount'].fillna(0, inplace=True)

# For text columns — fill with 'Unknown'
df['region'].fillna('Unknown', inplace=True)
df['customer_name'].fillna('Unknown', inplace=True)

# Verify no missing values remain
print(df.isnull().sum())

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub-category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

C:\Users\RUTVIK\AppData\Local\Temp\ipykernel_7300\1874821178.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sales'].fillna(df['sales'].median(), inplace=True)
C:\Users\RUTVIK\AppData\Local\Temp\ipykernel_7300\1874821178.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['profit'].fillna(0, inplace=True)
C:\Users\RUTVIK\AppData\Local\Temp\ipykernel_7300\1874821178.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['discount'].fillna(0, inplace=True)
C:\Users\RUTVIK\AppData\Local\Temp\ipykernel_7300\1874821178.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['region'].fillna('Unknown', inplace=True)
C:\Users\RUTVIK\AppData\Local\Temp\ipykernel_7300\1874821178.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['customer_name'].fillna('Unknown', inplace=True)

In [21]:
print(df.columns)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub-category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

In [22]:
#check duplicates before  
print(df.duplicated().sum())

#remove duplicate rows 
df.drop_duplicates(inplace = True)

0

In [23]:
#PROFIT MARGIN ADDING NEW COLUMN TO THE EXISTING DATA 
df['profit_margin_percentage'] = round((df['profit'] /df['sales']) * 100, 2)
print(df.columns)
print(df.profit_margin_percentage)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub-category',
       'product_name', 'sales', 'quantity', 'discount', 'profit',
       'profit_margin_percentage'],
      dtype='object')
0       16.00
1       30.00
2       47.00
3      -40.00
4       11.25
        ...
9989    16.25
9990    17.00
9991     7.50
9992    45.00
9993    30.00
Name: profit_margin_percentage, Length: 9994, dtype: float64

In [24]:
#SHIPPING DAYS (HOW LONG DELIVERY TOOK)
df['shipping_days'] = (df['ship_date'] -df['order_date']).dt.days

In [25]:
# 3. Extract Year, Month, Quarter from Order Date
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_month_name'] = df['order_date'].dt.strftime('%b')  # Jan, Feb...
df['order_quarter'] = df['order_date'].dt.quarter
df['month_year'] = df['order_date'].dt.strftime('%b-%Y')     # Jan-2021

In [26]:
print(df[['order_date', 'order_year', 'order_month', 
          'order_quarter', 'shipping_days', 
          'profit_margin_percentage']].head())

  order_date  order_year  order_month  order_quarter  shipping_days  \
0 2016-11-08        2016           11              4              3
1 2016-11-08        2016           11              4              3
2 2016-06-12        2016            6              2              4
3 2015-10-11        2015           10              4              7
4 2015-10-11        2015           10              4              7

   profit_margin_percentage
0                     16.00
1                     30.00
2                     47.00
3                    -40.00
4                     11.25

In [27]:
# Check for negative shipping days (data entry error)
print("Negative shipping days:", (df['shipping_days'] < 0).sum())

# Remove rows where shipping days is negative
df = df[df['shipping_days'] >= 0]

# Check for zero or negative sales (invalid orders)
print("Zero/Negative sales:", (df['sales'] <= 0).sum())

# Check profit margin extremes
print(df['profit_margin_percentage'].describe())

# See products with extreme negative margin
print(df[df['profit_margin_percentage'] < -50][['product_name', 
       'sales', 'profit', 'profit_margin_percentage']].head(10))

Negative shipping days: 0
Zero/Negative sales: 0
count    9994.000000
mean       12.031390
std        46.675436
min      -275.000000
25%         7.500000
50%        27.000000
75%        36.250000
max        50.000000
Name: profit_margin_percentage, dtype: float64
                                         product_name     sales     profit  \
14  Holmes Replacement Filter for HEPA Air Cleaner...    68.810  -123.8580
15   Storex DuraTech Recycled Plastic Frosted Binders     2.544    -3.8160
27  Riverside Palais Royal Lawyers Bookcase, Royal...  3083.430 -1665.0522
28  Avery Recycled Flexi-View Covers for Binding S...     9.618    -7.0532
32  Acco Pressboard Covers with Storage Hooks, 14 ...     6.858    -5.7150
36  Electrix Architect's Clamp-On Swing Arm Lamp, ...   190.920  -147.9630
75                                    Economy Binders     1.248    -1.9344
76                       6" Cubicle Wall Clock, Black     9.708    -5.8248
78  Eldon Expressions Desk Accessory, Wood Pencil ...    19.300   -14.4750
95  Flexible Leather- Look Classic Collection Ring...     5.682    -3.7880

    profit_margin_percentage
14                   -180.00
15                   -150.00
27                    -54.00
28                    -73.33
32                    -83.33
36                    -77.50
75                   -155.00
76                    -60.00
78                    -75.00
95                    -66.67

In [28]:
# Final shape check
print("Final dataset shape:", df.shape)

# Final missing value check
print("Missing values:\n", df.isnull().sum())

# Preview cleaned data
print(df.head())

# Save cleaned file
df.to_csv('superstore_utf8.csv', index=False, encoding='utf-8')

print(" Data cleaning complete! File saved as superstore_utf8.csv")

Final dataset shape: (9994, 28)
Missing values:
 row_id                      0
order_id                    0
order_date                  0
ship_date                   0
ship_mode                   0
customer_id                 0
customer_name               0
segment                     0
country                     0
city                        0
state                       0
postal_code                 0
region                      0
product_id                  0
category                    0
sub-category                0
product_name                0
sales                       0
quantity                    0
discount                    0
profit                      0
profit_margin_percentage    0
shipping_days               0
order_year                  0
order_month                 0
order_month_name            0
order_quarter               0
month_year                  0
dtype: int64
   row_id        order_id order_date  ship_date       ship_mode customer_id  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335

     customer_name    segment        country             city  ... quantity  \
0      Claire Gute   Consumer  United States        Henderson  ...        2
1      Claire Gute   Consumer  United States        Henderson  ...        3
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...        2
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...        5
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...        2

   discount    profit profit_margin_percentage shipping_days order_year  \
0      0.00   41.9136                    16.00             3       2016
1      0.00  219.5820                    30.00             3       2016
2      0.00    6.8714                    47.00             4       2016
3      0.45 -383.0310                   -40.00             7       2015
4      0.20    2.5164                    11.25             7       2015

  order_month  order_month_name  order_quarter  month_year
0          11               Nov              4    Nov-2016
1          11               Nov              4    Nov-2016
2           6               Jun              2    Jun-2016
3          10               Oct              4    Oct-2015
4          10               Oct              4    Oct-2015

[5 rows x 28 columns]
 Data cleaning complete! File saved as superstore_utf8.csv

In [29]:
from IPython.display import FileLink

df.to_csv('cleaned_data.csv', index=False)
FileLink('cleaned_data.csv')  # Creates a clickable download link in the notebook

C:\Users\RUTVIK\cleaned_data.csv